#!/usr/bin/env python3
"""Install myarch home files and machine integration.

The shell wrapper installs Python/Jinja and the package manifest first. This module
owns deterministic rendering, system integration, plugins, and runtime reloads.
"""

from __future__ import annotations

import argparse
import datetime as dt
import filecmp
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import tomllib
import urllib.request

from jinja2 import Environment, StrictUndefined

REPO = Path(__file__).resolve().parent
HOME = Path.home()
STATE = HOME / ".local/state/myarch"
MANIFEST = STATE / "installed-files.json"
BACKUPS = STATE / "backups"
THEME_STATE = HOME / ".config/myarch/theme"
DISCLAIMER = "NOTE! This file was generated by myarch; edit its source instead"
COLOR_RE = re.compile(r"^#[0-9a-fA-F]{6}$")
REQUIRED_THEME_KEYS = {
    "name", "background", "surface", "surface_hover", "foreground", "muted",
    "accent", "accent_alt", "urgent", "warning", "success", "quiet", "chill",
    "performance", "recording", "transcribing", "cleaning", "injecting",
    "selection_background", "selection_foreground", "cursor", "cursor_text", "palette",
}
VOXTYPE_RELEASE = "1.0.0-rc2"
VOXTYPE_ARTIFACTS = {
    "avx2": (
        "voxtype-1.0.0-rc2-linux-x86_64-onnx-avx2",
        "46614751fdc960bc8b9ddae478cb792c794efc8827315942ddd181e11883fb48",
    ),
    "avx512": (
        "voxtype-1.0.0-rc2-linux-x86_64-onnx-avx512",
        "425d650273220382f73a3bb4f8a563e0769f1c694eabb7c82701a919f44a689b",
    ),
}
MONO_FONT_FAMILY = "IoskeleyMonoTerm Nerd Font Mono"


def run(argv: list[str], *, check: bool = True, capture: bool = False, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(argv))
    return subprocess.run(argv, check=check, text=True, capture_output=capture, env=env)


def require_mono_font() -> None:
    resolved = run(
        ["fc-match", "--format=%{family}\\n", MONO_FONT_FAMILY],
        capture=True,
    ).stdout.splitlines()
    families = {family.strip() for line in resolved for family in line.split(",")}
    if MONO_FONT_FAMILY not in families:
        raise RuntimeError(
            f"required font is missing: {MONO_FONT_FAMILY}; "
            "run the myrig fonts target before installing myarch"
        )


def read_toml(path: Path) -> dict:
    with path.open("rb") as stream:
        return tomllib.load(stream)


def load_profile(name: str) -> dict:
    path = REPO / "profiles" / f"{name}.toml"
    if not path.is_file():
        choices = ", ".join(p.stem for p in sorted((REPO / "profiles").glob("*.toml")))
        raise SystemExit(f"unknown profile {name!r}; available profiles: {choices}")
    profile = read_toml(path)
    if profile.get("name") != name:
        raise SystemExit(f"{path}: name must be {name!r}")
    return profile


def load_theme(name: str) -> dict:
    path = REPO / "themes" / f"{name}.toml"
    if not path.is_file():
        choices = ", ".join(p.stem for p in sorted((REPO / "themes").glob("*.toml")))
        raise SystemExit(f"unknown theme {name!r}; available themes: {choices}")
    theme = read_toml(path)
    missing = REQUIRED_THEME_KEYS - theme.keys()
    extra = theme.keys() - REQUIRED_THEME_KEYS
    if missing or extra:
        raise SystemExit(f"{path}: theme key mismatch; missing={sorted(missing)}, extra={sorted(extra)}")
    for key, value in theme.items():
        if key in {"name", "palette"}:
            continue
        if not isinstance(value, str) or not COLOR_RE.fullmatch(value):
            raise SystemExit(f"{path}: {key} must be a #RRGGBB colour")
    if not isinstance(theme["palette"], list) or len(theme["palette"]) != 16 or not all(COLOR_RE.fullmatch(v) for v in theme["palette"]):
        raise SystemExit(f"{path}: palette must contain exactly 16 #RRGGBB colours")
    return theme


def comment_prefix(path: Path) -> str | None:
    name = path.name.removesuffix(".jinja")
    if name.endswith((".css", ".json")):
        return None
    if name.endswith(".jsonc"):
        return "//"
    if name.endswith(".lua"):
        return "--"
    if name.endswith(".ini") and "foot" not in path.parts:
        return ";"
    return "#"


def add_disclaimer(source: Path, rendered: str) -> str:
    prefix = comment_prefix(source)
    if prefix is None:
        return rendered
    note = f"{prefix} {DISCLAIMER}\n{prefix} Source: {source}"
    if rendered.startswith("#!"):
        first, separator, rest = rendered.partition("\n")
        return f"{first}\n{note}\n\n{rest}" if separator else f"{first}\n{note}\n"
    return f"{note}\n\n{rendered}"


def selected_home_sources(profile_name: str) -> list[Path]:
    sources: list[Path] = []
    for path in sorted((REPO / "home").glob("**/*")):
        if not path.is_file():
            continue
        rel = path.relative_to(REPO / "home")
        if "__pycache__" in rel.parts or path.suffix in {".pyc", ".pyo"}:
            continue
        if profile_name != "pocket4":
            if path.name.startswith("pocket4-") or rel == Path(".config/myarch/shell/pocket4.zsh"):
                continue
            if rel in {Path(".config/waybar/config-narrow.jsonc.jinja"), Path(".config/waybar/style-compact.css")}:
                continue
        sources.append(path)
    return sources


def destination_for(source: Path) -> Path:
    rel = source.relative_to(REPO / "home")
    if rel.suffix == ".jinja":
        rel = rel.with_suffix("")
    return HOME / rel


def backup_existing(destination: Path, stamp: str) -> None:
    if not destination.exists() and not destination.is_symlink():
        return
    backup = BACKUPS / stamp / destination.relative_to(HOME)
    backup.parent.mkdir(parents=True, exist_ok=True)
    if destination.is_symlink():
        target = os.readlink(destination)
        backup.with_suffix(backup.suffix + ".symlink").write_text(target)
    elif destination.is_file():
        shutil.copy2(destination, backup)
    else:
        raise RuntimeError(f"refusing to replace non-file destination: {destination}")


def atomic_write(destination: Path, content: str, mode: int, stamp: str) -> None:
    current = None
    if destination.exists() and not destination.is_symlink() and destination.is_file():
        current = destination.read_text(errors="surrogateescape")
    if current == content:
        os.chmod(destination, mode)
        return
    backup_existing(destination, stamp)
    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", dir=destination.parent, prefix=f".{destination.name}.", suffix=".tmp", delete=False) as stream:
        stream.write(content)
        temporary = Path(stream.name)
    try:
        os.chmod(temporary, mode)
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)


def install_symlink(source: Path, destination: Path, stamp: str) -> None:
    if destination.is_symlink() and Path(os.readlink(destination)) == source:
        return
    backup_existing(destination, stamp)
    if destination.exists() or destination.is_symlink():
        destination.unlink()
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.symlink_to(source)


def render_home(profile_name: str, profile: dict, theme_name: str, theme: dict) -> list[Path]:
    env = Environment(undefined=StrictUndefined, keep_trailing_newline=True, autoescape=False)
    context = {
        "home": HOME.as_posix(),
        "repo": REPO.as_posix(),
        "profile": profile,
        "theme": theme,
        "theme_name": theme_name,
        # Keep compatibility with the carefully documented source extracted from myrig.
        "targets": ["myarch", profile_name],
        "targets_str": f"myarch,{profile_name}",
        "myrig_path": (HOME / "mysetup/myrig").as_posix(),
    }
    stamp = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    installed: list[Path] = []

    for source in selected_home_sources(profile_name):
        destination = destination_for(source)
        if source.suffix == ".jinja":
            rendered = env.from_string(source.read_text()).render(**context)
            rendered = add_disclaimer(source, rendered)
            src_mode = stat.S_IMODE(source.stat().st_mode)
            # Respect a conventional 022 installation mode while preserving executability.
            mode = 0o644 | (src_mode & 0o111)
            atomic_write(destination, rendered, mode, stamp)
        else:
            install_symlink(source, destination, stamp)
        installed.append(destination)

    fragments = sorted((REPO / "src/hyprland").glob("*.lua.jinja"))
    if not fragments:
        raise RuntimeError("src/hyprland has no Lua fragments")
    source_text = "\n".join(fragment.read_text() for fragment in fragments)
    rendered_lua = env.from_string(source_text).render(**context)
    fragment_list = ", ".join(fragment.name for fragment in fragments)
    rendered_lua = f"-- {DISCLAIMER}\n-- Sources: {fragment_list}\n\n{rendered_lua}"
    hypr_destination = HOME / ".config/hypr/hyprland.lua"
    atomic_write(hypr_destination, rendered_lua, 0o644, stamp)
    installed.append(hypr_destination)

    previous: list[str] = []
    if MANIFEST.is_file():
        previous = json.loads(MANIFEST.read_text()).get("files", [])
    current = {path.as_posix() for path in installed}
    for old_name in previous:
        if old_name in current:
            continue
        old = Path(old_name)
        owned = old.is_symlink() and str(REPO) in os.readlink(old)
        if not owned and old.is_file() and not old.is_symlink():
            owned = DISCLAIMER in old.read_text(errors="ignore")[:1024]
        if owned:
            backup_existing(old, stamp)
            old.unlink()

    STATE.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(json.dumps({"profile": profile_name, "theme": theme_name, "files": sorted(current)}, indent=2) + "\n")
    THEME_STATE.parent.mkdir(parents=True, exist_ok=True)
    THEME_STATE.write_text(theme_name + "\n")
    return installed


def configure_system() -> None:
    source = REPO / "system/keyd/default.conf"
    probe = run(["sudo", "cmp", "-s", source.as_posix(), "/etc/keyd/default.conf"], check=False)
    keyd_changed = probe.returncode != 0
    if keyd_changed:
        run(["sudo", "install", "-Dm644", source.as_posix(), "/etc/keyd/default.conf"])
    run(["sudo", "systemctl", "enable", "--now", "bluetooth.service", "keyd.service"])
    if keyd_changed:
        run(["sudo", "systemctl", "restart", "keyd.service"])
    run(["sudo", "timedatectl", "set-ntp", "true"])
    run(["fc-cache", "-f"])


def live_hyprland_env() -> dict[str, str] | None:
    result = run(["hyprctl", "instances", "-j"], check=False, capture=True)
    if result.returncode != 0:
        return None
    try:
        instances = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None
    if not instances:
        return None
    environment = os.environ.copy()
    environment["HYPRLAND_INSTANCE_SIGNATURE"] = instances[0]["instance"]
    return environment


def configure_plugins(profile: dict, environment: dict[str, str] | None) -> None:
    if environment is None:
        print("myarch: no running Hyprland instance; runtime plugin build is deferred", file=sys.stderr)
        return
    run(["hyprpm", "update"], env=environment)
    output = run(["hyprpm", "list"], capture=True, env=environment).stdout
    plugins = [("https://github.com/sandwichfarm/hyprexpo", "hyprexpo")]
    if profile["plugins"]["hyprgrass"]:
        plugins.append(("https://github.com/horriblename/hyprgrass", "hyprgrass"))
    for url, name in plugins:
        if name not in output:
            run(["hyprpm", "add", url], env=environment)
        run(["hyprpm", "enable", name], env=environment)


def stop_replaced_dictation() -> None:
    """Stop the old daemon before its generated configuration is retired."""
    old_cli = shutil.which("mydictation")
    if old_cli is not None:
        run([old_cli, "daemon", "stop"], check=False)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def install_voxtype_release(variant: str) -> Path:
    artifact, expected_sha256 = VOXTYPE_ARTIFACTS[variant]
    destination = Path("/usr/local/lib/myarch") / artifact
    if not destination.is_file() or sha256(destination) != expected_sha256:
        cache = STATE / "downloads" / artifact
        cache.parent.mkdir(parents=True, exist_ok=True)
        if not cache.is_file() or sha256(cache) != expected_sha256:
            url = f"https://github.com/peteonrails/voxtype/releases/download/v{VOXTYPE_RELEASE}/{artifact}"
            with tempfile.NamedTemporaryFile(
                "wb", dir=cache.parent, prefix=f".{artifact}.", delete=False
            ) as stream:
                temporary = Path(stream.name)
            try:
                with urllib.request.urlopen(url, timeout=60) as response:
                    with temporary.open("wb") as stream:
                        shutil.copyfileobj(response, stream)
                actual_sha256 = sha256(temporary)
                if actual_sha256 != expected_sha256:
                    raise RuntimeError(
                        f"Voxtype {VOXTYPE_RELEASE} checksum mismatch: "
                        f"expected {expected_sha256}, got {actual_sha256}"
                    )
                os.replace(temporary, cache)
            finally:
                temporary.unlink(missing_ok=True)
        run(["sudo", "install", "-Dm755", cache.as_posix(), destination.as_posix()])
    run(["sudo", "ln", "-sfn", destination.as_posix(), "/usr/bin/voxtype"])
    return destination


def prepare_external(profile: dict) -> None:
    wallpaper_dir = Path(profile["external"]["wallpaper_directory"]).expanduser()
    if not wallpaper_dir.is_dir():
        raise RuntimeError(f"required wallpaper directory is missing: {wallpaper_dir}")
    if not profile["voxtype"]:
        return

    run(["systemctl", "--user", "stop", "voxtype.service"], check=False)
    cpu_flags = Path("/proc/cpuinfo").read_text()
    variant = "avx512" if "avx512f" in cpu_flags else "avx2"
    binary = install_voxtype_release(variant)
    version = run([binary.as_posix(), "--version"], capture=True).stdout.strip()
    if version != "voxtype 1.0.0":
        raise RuntimeError(f"unexpected Voxtype {VOXTYPE_RELEASE} version output: {version!r}")
    model_dir = HOME / ".local/share/voxtype/models/parakeet-tdt-0.6b-v3-int8"
    model_files = (
        "encoder-model.int8.onnx", "decoder_joint-model.int8.onnx",
        "vocab.txt", "config.json",
    )
    if not all((model_dir / name).is_file() for name in model_files):
        run([
            "voxtype", "setup", "--download", "--no-post-install",
            "--model", "parakeet-tdt-0.6b-v3-int8",
        ])
    missing = [name for name in model_files if not (model_dir / name).is_file()]
    if missing:
        raise RuntimeError(f"Voxtype Parakeet model is incomplete; missing: {missing}")


def start_external(profile: dict, environment: dict[str, str] | None) -> None:
    if profile["voxtype"]:
        run(["systemctl", "--user", "daemon-reload"])
        run(["systemctl", "--user", "enable", "voxtype.service"])
        if environment is not None:
            run(["systemctl", "--user", "start", "voxtype.service"])


def pause_autoreload(environment: dict[str, str] | None) -> tuple[bool, bool] | None:
    if environment is None:
        return None
    values: list[bool] = []
    for option in ("misc.disable_autoreload", "debug.suppress_errors"):
        result = run(["hyprctl", "-j", "getoption", option], capture=True, env=environment)
        values.append(bool(json.loads(result.stdout)["bool"]))
    run(["hyprctl", "eval", "hl.config({ misc = { disable_autoreload = true }, debug = { suppress_errors = true } })"], env=environment)
    return values[0], values[1]


def resume_autoreload(environment: dict[str, str] | None, previous: tuple[bool, bool] | None) -> None:
    if environment is None or previous is None:
        return
    disable, suppress = (str(value).lower() for value in previous)
    run(["hyprctl", "eval", f"hl.config({{ debug = {{ suppress_errors = {suppress} }} }})"], check=False, env=environment)
    run(["hyprctl", "reload"], check=False, env=environment)
    run(["hyprctl", "eval", f"hl.config({{ misc = {{ disable_autoreload = {disable} }}, debug = {{ suppress_errors = {suppress} }} }})"], check=False, env=environment)


def restart_user_surfaces(profile_name: str, environment: dict[str, str] | None) -> None:
    if environment is None:
        return
    # restart-bar dispatches to the Pocket launcher when that profile installed it,
    # and to plain Waybar on IdeaPad. It also waits for old layer surfaces to drain.
    run([(HOME / ".mybin/restart-bar").as_posix()], env=environment)
    run(["makoctl", "reload"], check=False, env=environment)


def migrate_myrig_state() -> None:
    """Carry state whose owning scripts moved from myrig into myarch."""
    old = HOME / ".local/state/myrig"
    STATE.mkdir(parents=True, exist_ok=True)
    # TODO(cleanup): remove this migration after myarch has been installed on Pocket 4
    # and IdeaPad; each state file is copied only when its myarch destination is absent.
    names = [
        "display-mode.layout", "display-mode.workspaces", "display-mode.active",
        "display-mode.focus", "display-mode.base", "wallpaper.pin", "wallpaper.due",
    ]
    for name in names:
        source = old / name
        destination = STATE / name
        if source.is_file() and not destination.exists():
            shutil.copy2(source, destination)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", required=True, choices=[p.stem for p in sorted((REPO / "profiles").glob("*.toml"))])
    parser.add_argument("--theme", choices=[p.stem for p in sorted((REPO / "themes").glob("*.toml"))])
    parser.add_argument("--config-only", action="store_true")
    parser.add_argument("--skip-runtime", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    profile = load_profile(args.profile)
    theme_name = args.theme
    if theme_name is None:
        if not THEME_STATE.is_file():
            raise SystemExit("--theme is required for the first installation")
        theme_name = THEME_STATE.read_text().strip()
        if not theme_name:
            raise SystemExit(f"theme state is empty: {THEME_STATE}")
    theme = load_theme(theme_name)
    require_mono_font()
    environment = None if args.skip_runtime else live_hyprland_env()
    migrate_myrig_state()
    previous = pause_autoreload(environment)
    try:
        stop_replaced_dictation()
        if not args.config_only:
            prepare_external(profile)
        render_home(args.profile, profile, theme_name, theme)
        if not args.config_only:
            configure_system()
            start_external(profile, environment)
            configure_plugins(profile, environment)
    finally:
        resume_autoreload(environment, previous)
    restart_user_surfaces(args.profile, environment)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
