name = "ideapad"
terminal = "kitty"
battery = "BAT1"
touchscreen = false
voxtype = true

[dictation]
source_volume = "unchanged"

[plugins]
hyprexpo = true
hyprgrass = false

[external]
wallpaper_directory = "~/Pictures/wallpapers"
