name = "pocket4"
terminal = "foot"
battery = "BATT"
touchscreen = true
mydictation = true

[plugins]
hyprexpo = true
hyprgrass = true

[external]
mydictation_source = "~/mysetup/mydictation"
wallpaper_directory = "~/Pictures/wallpapers"
