name = "pocket4"
terminal = "foot"
battery = "BATT"
touchscreen = true
voxtype = true

[dictation]
source_volume = "25%"

[plugins]
hyprexpo = true
hyprgrass = true

[external]
wallpaper_directory = "~/Pictures/wallpapers"
